name: Binaries
description: build standalone executables using PyInstaller

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
  workflow_dispatch:

jobs:
  build-x64:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'
      - name: Setup virtual env
        run: |
          python -m venv ./venv
      - name: Build exe for POSIX
        if: runner.os != 'Windows'
        run: |
          ./venv/bin/python -m pip install --upgrade pip
          ./venv/bin/python -m pip install -r requirements_dev.txt
          ./venv/bin/python -m pip install .
          ./venv/bin/python -m pip install pyinstaller
          fidodir=$(./venv/bin/python -c "import fido2;from os import path as op;print(op.dirname(fido2.__file__))")
          omddir=$(./venv/bin/python -c "import orderedmultidict;from os import path as op;print(op.dirname(orderedmultidict.__file__))")
          ./venv/bin/python -m PyInstaller -F --hidden-import=gimme_aws_creds --add-data "$fidodir/public_suffix_list.dat:fido2" --add-data "$omddir/__version__.py:orderedmultidict" bin/gimme-aws-creds
      - name: Upload POSIX executable
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: gimme-aws-creds-${{ matrix.os }}-x64
          path: dist/gimme-aws-creds
      - name: Build exe for Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./venv/Scripts/python -m pip install --upgrade pip
          ./venv/Scripts/python -m pip install -r requirements_dev.txt
          ./venv/Scripts/python -m pip install .
          ./venv/Scripts/python -m pip install pyinstaller
          $fidodir = ./venv/Scripts/python -c "import fido2;from os import path as op;print(op.dirname(fido2.__file__))"
          $omddir  = ./venv/Scripts/python -c "import orderedmultidict;from os import path as op;print(op.dirname(orderedmultidict.__file__))"
          ./venv/Scripts/python -m PyInstaller -F --hidden-import=gimme_aws_creds --add-data "$fidodir/public_suffix_list.dat;fido2" --add-data "$omddir/__version__.py;orderedmultidict" bin/gimme-aws-creds
      - name: Upload Windows executable
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: gimme-aws-creds-windows-x64
          path: dist/gimme-aws-creds.exe

  build-arm:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-arm, macos-latest, windows-11-arm]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'arm64'
      - name: Setup virtual env
        run: |
          python -m venv ./venv
      - name: Build exe for POSIX
        if: runner.os != 'Windows'
        run: |
          ./venv/bin/python -m pip install --upgrade pip
          ./venv/bin/python -m pip install -r requirements_dev.txt
          ./venv/bin/python -m pip install .
          ./venv/bin/python -m pip install pyinstaller
          fidodir=$(./venv/bin/python -c "import fido2;from os import path as op;print(op.dirname(fido2.__file__))")
          omddir=$(./venv/bin/python -c "import orderedmultidict;from os import path as op;print(op.dirname(orderedmultidict.__file__))")
          ./venv/bin/python -m PyInstaller -F --hidden-import=gimme_aws_creds --add-data "$fidodir/public_suffix_list.dat:fido2" --add-data "$omddir/__version__.py:orderedmultidict" bin/gimme-aws-creds
      - name: Upload POSIX executable
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: gimme-aws-creds-${{ matrix.os }}-arm64
          path: dist/gimme-aws-creds
      - name: Build exe for Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./venv/Scripts/python -m pip install --upgrade pip
          ./venv/Scripts/python -m pip install --only-binary=:all: -r requirements_dev.txt
          ./venv/Scripts/python -m pip install .
          ./venv/Scripts/python -m pip install pyinstaller
          $fidodir = ./venv/Scripts/python -c "import fido2;from os import path as op;print(op.dirname(fido2.__file__))"
          $omddir  = ./venv/Scripts/python -c "import orderedmultidict;from os import path as op;print(op.dirname(orderedmultidict.__file__))"
          ./venv/Scripts/python -m PyInstaller -F --hidden-import=gimme_aws_creds --add-data "$fidodir/public_suffix_list.dat;fido2" --add-data "$omddir/__version__.py;orderedmultidict" bin/gimme-aws-creds
      - name: Upload Windows executable
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: gimme-aws-creds-windows-arm64
          path: dist/gimme-aws-creds.exe
