name: Release

description: Create a GitHub release and attach built binaries when a version tag is pushed

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    if: github.repository == 'warnermedia/gimme-aws-creds'
    runs-on: ubuntu-latest
    steps:
      - name: get id of run with latest binaries
        id: get_run_id
        run: |
            run_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/actions/workflows/binaries.yml/runs?status=success&per_page=1" | \
            jq -r '.workflow_runs[0].id')
            if [ -z "$run_id" ] || [ "$run_id" = "null" ]; then
              echo "No successful workflow runs found for binaries.yml. Cannot proceed with release." >&2
              exit 1
            fi
            printf 'run_id=%s\n' "$run_id" >>"$GITHUB_OUTPUT"
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          run-id: ${{ steps.get_run_id.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive artifacts
        run: |
            cd artifacts
            for dir in */; do
               if [ -n "$(find "$dir" -mindepth 1 -print -quit)" ]; then
                 (cd "$dir" && zip -r "../${dir%/}.zip" .)
               else
                 echo "Skipping $dir: directory is empty"
               fi
            done
      - name: Create release and upload assets
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "artifacts/*.zip"
          tag: ${{ github.ref_name }}
