name: Release

description: Create a GitHub release and attach built binaries when a version tag is pushed

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    if: github.repository == 'warnermedia/gimme-aws-creds'
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
